"""
discover_slugs.py — discovers NEW Legistar slugs by testing hundreds
of city name patterns against the live API.

Run with: python discover_slugs.py
Results auto-added to scrapers/legistar.py

This is the key to getting more packets — finding cities we don't have yet.
"""

import sys, os, requests, time, json
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from concurrent.futures import ThreadPoolExecutor, as_completed
from colorama import Fore, Style, init as colorama_init
colorama_init(autoreset=True)

HEADERS = {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) Chrome/124.0.0.0 Safari/537.36"}
TIMEOUT = 8

# Load existing slugs so we don't re-test them
from scrapers.legistar import LEGISTAR_CITIES
existing = set(LEGISTAR_CITIES.keys())

# Generate candidates from all US cities
# Format: (slug_to_test, state, display_name)
CANDIDATES = [
    # New York
    ("nyc", "New York", "New York City"),
    ("newyorkcity", "New York", "New York City"),
    ("buffalo", "New York", "Buffalo"),
    ("rochester", "New York", "Rochester"),
    ("yonkers", "New York", "Yonkers"),
    ("albany", "New York", "Albany"),
    ("schenectady", "New York", "Schenectady"),
    ("utica", "New York", "Utica"),
    ("troy", "New York", "Troy"),
    ("mountvernon", "New York", "Mount Vernon"),
    ("newrochelle", "New York", "New Rochelle"),
    ("whiteplains", "New York", "White Plains"),
    ("nassaucounty", "New York", "Nassau County"),
    ("suffolkcounty", "New York", "Suffolk County"),
    ("westchestercounty", "New York", "Westchester County"),
    ("monroecounty", "New York", "Monroe County"),
    ("ericounty", "New York", "Erie County"),
    ("onondagacounty", "New York", "Onondaga County"),
    # California
    ("lacity", "California", "Los Angeles"),
    ("lacounty", "California", "Los Angeles County"),
    ("sfgov", "California", "San Francisco"),
    ("sandiego", "California", "San Diego"),
    ("sanjose", "California", "San Jose"),
    ("fresno", "California", "Fresno"),
    ("sacramento", "California", "Sacramento"),
    ("longbeachca", "California", "Long Beach"),
    ("oakland", "California", "Oakland"),
    ("bakersfield", "California", "Bakersfield"),
    ("anaheim", "California", "Anaheim"),
    ("riverside", "California", "Riverside"),
    ("santaana", "California", "Santa Ana"),
    ("irvine", "California", "Irvine"),
    ("chula-vista", "California", "Chula Vista"),
    ("fremont", "California", "Fremont"),
    ("san-bernardino", "California", "San Bernardino"),
    ("modesto", "California", "Modesto"),
    ("fontana", "California", "Fontana"),
    ("oxnard", "California", "Oxnard"),
    ("moreno-valley", "California", "Moreno Valley"),
    ("glendale", "California", "Glendale"),
    ("huntington-beach", "California", "Huntington Beach"),
    ("santa-clarita", "California", "Santa Clarita"),
    ("garden-grove", "California", "Garden Grove"),
    ("santa-rosa", "California", "Santa Rosa"),
    ("oceanside", "California", "Oceanside"),
    ("elk-grove", "California", "Elk Grove"),
    ("corona", "California", "Corona"),
    ("lancaster", "California", "Lancaster"),
    ("salinas", "California", "Salinas"),
    ("palmdale", "California", "Palmdale"),
    ("pomona", "California", "Pomona"),
    ("torrance", "California", "Torrance"),
    ("hayward", "California", "Hayward"),
    ("escondido", "California", "Escondido"),
    ("pasadena", "California", "Pasadena"),
    ("sunnyvale", "California", "Sunnyvale"),
    ("thousand-oaks", "California", "Thousand Oaks"),
    ("simi-valley", "California", "Simi Valley"),
    ("visalia", "California", "Visalia"),
    ("orange", "California", "Orange"),
    ("fullerton", "California", "Fullerton"),
    ("murrieta", "California", "Murrieta"),
    ("concord", "California", "Concord"),
    ("west-covina", "California", "West Covina"),
    ("roseville", "California", "Roseville"),
    ("victorville", "California", "Victorville"),
    ("santa-clara", "California", "Santa Clara"),
    ("clovis", "California", "Clovis"),
    ("vallejo", "California", "Vallejo"),
    ("berkeley", "California", "Berkeley"),
    ("antioch", "California", "Antioch"),
    ("richmond", "California", "Richmond"),
    ("ventura", "California", "Ventura"),
    ("temecula", "California", "Temecula"),
    ("costa-mesa", "California", "Costa Mesa"),
    ("inglewood", "California", "Inglewood"),
    ("carlsbad", "California", "Carlsbad"),
    ("fairfield", "California", "Fairfield"),
    ("petaluma", "California", "Petaluma"),
    ("santa-barbara", "California", "Santa Barbara"),
    ("napa", "California", "Napa"),
    ("chico", "California", "Chico"),
    ("redding", "California", "Redding"),
    ("el-monte", "California", "El Monte"),
    ("downey", "California", "Downey"),
    ("west-sacramento", "California", "West Sacramento"),
    ("san-mateo", "California", "San Mateo"),
    ("el-cajon", "California", "El Cajon"),
    ("rialto", "California", "Rialto"),
    ("daly-city", "California", "Daly City"),
    ("burbank", "California", "Burbank"),
    ("san-buenaventura", "California", "Ventura"),
    ("compton", "California", "Compton"),
    ("norwalk", "California", "Norwalk"),
    ("el-cajon", "California", "El Cajon"),
    ("orange-county", "California", "Orange County"),
    ("san-diego-county", "California", "San Diego County"),
    ("sacramento-county", "California", "Sacramento County"),
    ("riverside-county", "California", "Riverside County"),
    ("contra-costa", "California", "Contra Costa County"),
    ("alameda-county", "California", "Alameda County"),
    ("santa-clara-county", "California", "Santa Clara County"),
    # Texas
    ("austintexas", "Texas", "Austin"),
    ("houston", "Texas", "Houston"),
    ("sanantonio", "Texas", "San Antonio"),
    ("dallas", "Texas", "Dallas"),
    ("fortworth", "Texas", "Fort Worth"),
    ("elpaso", "Texas", "El Paso"),
    ("arlington", "Texas", "Arlington"),
    ("corpuschristi", "Texas", "Corpus Christi"),
    ("plano", "Texas", "Plano"),
    ("laredo", "Texas", "Laredo"),
    ("lubbock", "Texas", "Lubbock"),
    ("garland", "Texas", "Garland"),
    ("irving", "Texas", "Irving"),
    ("amarillo", "Texas", "Amarillo"),
    ("grandprairie", "Texas", "Grand Prairie"),
    ("brownsville", "Texas", "Brownsville"),
    ("killeen", "Texas", "Killeen"),
    ("mckinney", "Texas", "McKinney"),
    ("frisco", "Texas", "Frisco"),
    ("denton", "Texas", "Denton"),
    ("mcallen", "Texas", "McAllen"),
    ("mesquite", "Texas", "Mesquite"),
    ("waco", "Texas", "Waco"),
    ("carrollton", "Texas", "Carrollton"),
    ("midland", "Texas", "Midland"),
    ("lewisville", "Texas", "Lewisville"),
    ("richardson", "Texas", "Richardson"),
    ("pasadenatx", "Texas", "Pasadena"),
    ("tyler", "Texas", "Tyler"),
    ("pearland", "Texas", "Pearland"),
    ("abilene", "Texas", "Abilene"),
    ("odessa", "Texas", "Odessa"),
    ("beaumont", "Texas", "Beaumont"),
    ("roundrock", "Texas", "Round Rock"),
    ("wichitafalls", "Texas", "Wichita Falls"),
    ("allen", "Texas", "Allen"),
    ("sanmarcos", "Texas", "San Marcos"),
    ("bryancollegestation", "Texas", "Bryan"),
    ("leaguecity", "Texas", "League City"),
    ("sugarland", "Texas", "Sugar Land"),
    ("edinburg", "Texas", "Edinburg"),
    ("dallas-county", "Texas", "Dallas County"),
    ("tarrant-county", "Texas", "Tarrant County"),
    ("harris-county", "Texas", "Harris County"),
    ("travis-county", "Texas", "Travis County"),
    ("bexar-county", "Texas", "Bexar County"),
    ("collin-county", "Texas", "Collin County"),
    ("denton-county", "Texas", "Denton County"),
    # Florida
    ("miami", "Florida", "Miami"),
    ("orlando", "Florida", "Orlando"),
    ("tampa", "Florida", "Tampa"),
    ("jacksonville", "Florida", "Jacksonville"),
    ("stpete", "Florida", "St. Petersburg"),
    ("hialeah", "Florida", "Hialeah"),
    ("tallahassee", "Florida", "Tallahassee"),
    ("fort-lauderdale", "Florida", "Fort Lauderdale"),
    ("portst-lucie", "Florida", "Port St. Lucie"),
    ("capecoral", "Florida", "Cape Coral"),
    ("pembroke-pines", "Florida", "Pembroke Pines"),
    ("hollywood", "Florida", "Hollywood"),
    ("gainesville", "Florida", "Gainesville"),
    ("miramar", "Florida", "Miramar"),
    ("coral-springs", "Florida", "Coral Springs"),
    ("lakeland", "Florida", "Lakeland"),
    ("clearwater", "Florida", "Clearwater"),
    ("west-palm-beach", "Florida", "West Palm Beach"),
    ("pompano-beach", "Florida", "Pompano Beach"),
    ("palm-bay", "Florida", "Palm Bay"),
    ("davie", "Florida", "Davie"),
    ("boca-raton", "Florida", "Boca Raton"),
    ("fort-myers", "Florida", "Fort Myers"),
    ("deltona", "Florida", "Deltona"),
    ("plantation", "Florida", "Plantation"),
    ("sunrise", "Florida", "Sunrise"),
    ("pensacola", "Florida", "Pensacola"),
    ("sarasota", "Florida", "Sarasota"),
    ("bradenton", "Florida", "Bradenton"),
    ("ocala", "Florida", "Ocala"),
    ("daytona-beach", "Florida", "Daytona Beach"),
    ("kissimmee", "Florida", "Kissimmee"),
    ("broward", "Florida", "Broward County"),
    ("palmbeach", "Florida", "Palm Beach County"),
    ("miamidade", "Florida", "Miami-Dade County"),
    ("hillsborough", "Florida", "Hillsborough County"),
    ("orange-county-fl", "Florida", "Orange County"),
    ("pinellas", "Florida", "Pinellas County"),
    # Illinois
    ("chicago", "Illinois", "Chicago"),
    ("aurora", "Illinois", "Aurora"),
    ("joliet", "Illinois", "Joliet"),
    ("rockford", "Illinois", "Rockford"),
    ("springfield", "Illinois", "Springfield"),
    ("elgin", "Illinois", "Elgin"),
    ("peoria", "Illinois", "Peoria"),
    ("champaign", "Illinois", "Champaign"),
    ("waukegan", "Illinois", "Waukegan"),
    ("cicero", "Illinois", "Cicero"),
    ("bloomington", "Illinois", "Bloomington"),
    ("naperville", "Illinois", "Naperville"),
    ("evanston", "Illinois", "Evanston"),
    ("cook", "Illinois", "Cook County"),
    ("dupage", "Illinois", "DuPage County"),
    ("kane", "Illinois", "Kane County"),
    ("lake-county-il", "Illinois", "Lake County"),
    ("will-county", "Illinois", "Will County"),
    ("mchenry-county", "Illinois", "McHenry County"),
    ("winnebago", "Illinois", "Winnebago County"),
    # Pennsylvania
    ("phila", "Pennsylvania", "Philadelphia"),
    ("pittsburgh", "Pennsylvania", "Pittsburgh"),
    ("allentown", "Pennsylvania", "Allentown"),
    ("erie", "Pennsylvania", "Erie"),
    ("reading", "Pennsylvania", "Reading"),
    ("scranton", "Pennsylvania", "Scranton"),
    ("bethlehem", "Pennsylvania", "Bethlehem"),
    ("lancaster", "Pennsylvania", "Lancaster"),
    ("harrisburg", "Pennsylvania", "Harrisburg"),
    ("york-city", "Pennsylvania", "York"),
    ("allegheny", "Pennsylvania", "Allegheny County"),
    ("montgomery-county-pa", "Pennsylvania", "Montgomery County"),
    ("delaware-county-pa", "Pennsylvania", "Delaware County"),
    ("bucks-county", "Pennsylvania", "Bucks County"),
    # Ohio
    ("columbus", "Ohio", "Columbus"),
    ("cleveland", "Ohio", "Cleveland"),
    ("cincinnati", "Ohio", "Cincinnati"),
    ("toledo", "Ohio", "Toledo"),
    ("akron", "Ohio", "Akron"),
    ("dayton", "Ohio", "Dayton"),
    ("parma", "Ohio", "Parma"),
    ("canton", "Ohio", "Canton"),
    ("lorain", "Ohio", "Lorain"),
    ("hamilton", "Ohio", "Hamilton"),
    ("youngstown", "Ohio", "Youngstown"),
    ("springfield-oh", "Ohio", "Springfield"),
    ("kettering", "Ohio", "Kettering"),
    ("elyria", "Ohio", "Elyria"),
    ("newark-oh", "Ohio", "Newark"),
    ("cuyahoga", "Ohio", "Cuyahoga County"),
    ("franklin-county", "Ohio", "Franklin County"),
    ("hamilton-county", "Ohio", "Hamilton County"),
    ("summit", "Ohio", "Summit County"),
    ("montgomery-county-oh", "Ohio", "Montgomery County"),
    # Michigan
    ("detroit", "Michigan", "Detroit"),
    ("grandrapids", "Michigan", "Grand Rapids"),
    ("warren", "Michigan", "Warren"),
    ("sterling-heights", "Michigan", "Sterling Heights"),
    ("lansing", "Michigan", "Lansing"),
    ("ann-arbor", "Michigan", "Ann Arbor"),
    ("flint", "Michigan", "Flint"),
    ("dearborn", "Michigan", "Dearborn"),
    ("livonia", "Michigan", "Livonia"),
    ("westland", "Michigan", "Westland"),
    ("kalamazoo", "Michigan", "Kalamazoo"),
    ("wyoming", "Michigan", "Wyoming"),
    ("southfield", "Michigan", "Southfield"),
    ("rochester-hills", "Michigan", "Rochester Hills"),
    ("waynecounty", "Michigan", "Wayne County"),
    ("oakland-county", "Michigan", "Oakland County"),
    ("macomb-county", "Michigan", "Macomb County"),
    ("kent-county", "Michigan", "Kent County"),
    # Georgia
    ("atlanta", "Georgia", "Atlanta"),
    ("augustaga", "Georgia", "Augusta"),
    ("columbusga", "Georgia", "Columbus"),
    ("savannah", "Georgia", "Savannah"),
    ("athens", "Georgia", "Athens"),
    ("sandy-springs", "Georgia", "Sandy Springs"),
    ("roswell", "Georgia", "Roswell"),
    ("macon", "Georgia", "Macon"),
    ("albany-ga", "Georgia", "Albany"),
    ("warner-robins", "Georgia", "Warner Robins"),
    ("fulton", "Georgia", "Fulton County"),
    ("gwinnett", "Georgia", "Gwinnett County"),
    ("dekalb", "Georgia", "DeKalb County"),
    ("cobb", "Georgia", "Cobb County"),
    ("chatham", "Georgia", "Chatham County"),
    # North Carolina
    ("charlotte", "North Carolina", "Charlotte"),
    ("raleigh", "North Carolina", "Raleigh"),
    ("greensboro", "North Carolina", "Greensboro"),
    ("durham", "North Carolina", "Durham"),
    ("winston-salem", "North Carolina", "Winston-Salem"),
    ("fayetteville", "North Carolina", "Fayetteville"),
    ("cary", "North Carolina", "Cary"),
    ("wilmington", "North Carolina", "Wilmington"),
    ("high-point", "North Carolina", "High Point"),
    ("concord-nc", "North Carolina", "Concord"),
    ("greenville-nc", "North Carolina", "Greenville"),
    ("asheville", "North Carolina", "Asheville"),
    ("chapel-hill", "North Carolina", "Chapel Hill"),
    ("gastonia", "North Carolina", "Gastonia"),
    ("wake-county", "North Carolina", "Wake County"),
    ("mecklenburg", "North Carolina", "Mecklenburg County"),
    ("guilford", "North Carolina", "Guilford County"),
    ("forsyth", "North Carolina", "Forsyth County"),
    ("cumberland-nc", "North Carolina", "Cumberland County"),
    # Tennessee
    ("nashville", "Tennessee", "Nashville"),
    ("memphis", "Tennessee", "Memphis"),
    ("knoxville", "Tennessee", "Knoxville"),
    ("chattanooga", "Tennessee", "Chattanooga"),
    ("clarksville", "Tennessee", "Clarksville"),
    ("murfreesboro", "Tennessee", "Murfreesboro"),
    ("franklin", "Tennessee", "Franklin"),
    ("jackson", "Tennessee", "Jackson"),
    ("johnson-city", "Tennessee", "Johnson City"),
    ("kingsport", "Tennessee", "Kingsport"),
    ("shelby-county", "Tennessee", "Shelby County"),
    ("knox-county", "Tennessee", "Knox County"),
    ("hamilton-county-tn", "Tennessee", "Hamilton County"),
    # Arizona
    ("phoenix", "Arizona", "Phoenix"),
    ("tucson", "Arizona", "Tucson"),
    ("mesa", "Arizona", "Mesa"),
    ("chandler", "Arizona", "Chandler"),
    ("scottsdale", "Arizona", "Scottsdale"),
    ("gilbert", "Arizona", "Gilbert"),
    ("tempe", "Arizona", "Tempe"),
    ("peoria", "Arizona", "Peoria"),
    ("glendale-az", "Arizona", "Glendale"),
    ("surprise", "Arizona", "Surprise"),
    ("goodyear", "Arizona", "Goodyear"),
    ("avondale", "Arizona", "Avondale"),
    ("flagstaff", "Arizona", "Flagstaff"),
    ("yuma", "Arizona", "Yuma"),
    ("maricopa", "Arizona", "Maricopa County"),
    ("pima", "Arizona", "Pima County"),
    # Washington
    ("seattle", "Washington", "Seattle"),
    ("spokane", "Washington", "Spokane"),
    ("tacoma", "Washington", "Tacoma"),
    ("vancouver", "Washington", "Vancouver"),
    ("bellevue", "Washington", "Bellevue"),
    ("everett", "Washington", "Everett"),
    ("renton", "Washington", "Renton"),
    ("spokane-valley", "Washington", "Spokane Valley"),
    ("kirkland", "Washington", "Kirkland"),
    ("kennewick", "Washington", "Kennewick"),
    ("kent", "Washington", "Kent"),
    ("bellingham", "Washington", "Bellingham"),
    ("yakima", "Washington", "Yakima"),
    ("redmond", "Washington", "Redmond"),
    ("marysville", "Washington", "Marysville"),
    ("federal-way", "Washington", "Federal Way"),
    ("olympia", "Washington", "Olympia"),
    ("auburn", "Washington", "Auburn"),
    ("lacey", "Washington", "Lacey"),
    ("richland", "Washington", "Richland"),
    ("kingcounty", "Washington", "King County"),
    ("pierce", "Washington", "Pierce County"),
    ("snohomish", "Washington", "Snohomish County"),
    ("clark-county", "Washington", "Clark County"),
    # Massachusetts
    ("boston", "Massachusetts", "Boston"),
    ("worcester", "Massachusetts", "Worcester"),
    ("springfield-ma", "Massachusetts", "Springfield"),
    ("lowell", "Massachusetts", "Lowell"),
    ("cambridge", "Massachusetts", "Cambridge"),
    ("new-bedford", "Massachusetts", "New Bedford"),
    ("brockton", "Massachusetts", "Brockton"),
    ("quincy", "Massachusetts", "Quincy"),
    ("lynn", "Massachusetts", "Lynn"),
    ("fall-river", "Massachusetts", "Fall River"),
    ("newton", "Massachusetts", "Newton"),
    ("lawrence", "Massachusetts", "Lawrence"),
    ("somerville", "Massachusetts", "Somerville"),
    ("framingham", "Massachusetts", "Framingham"),
    ("haverhill", "Massachusetts", "Haverhill"),
    ("waltham", "Massachusetts", "Waltham"),
    ("malden", "Massachusetts", "Malden"),
    ("medford", "Massachusetts", "Medford"),
    ("taunton", "Massachusetts", "Taunton"),
    ("chicopee", "Massachusetts", "Chicopee"),
    ("middlesex-county", "Massachusetts", "Middlesex County"),
    ("suffolk-county-ma", "Massachusetts", "Suffolk County"),
    # Indiana
    ("indianapolis", "Indiana", "Indianapolis"),
    ("fortwayne", "Indiana", "Fort Wayne"),
    ("evansville", "Indiana", "Evansville"),
    ("southbend", "Indiana", "South Bend"),
    ("carmel", "Indiana", "Carmel"),
    ("fishers", "Indiana", "Fishers"),
    ("bloomington-in", "Indiana", "Bloomington"),
    ("hammond", "Indiana", "Hammond"),
    ("gary", "Indiana", "Gary"),
    ("lafayette", "Indiana", "Lafayette"),
    ("muncie", "Indiana", "Muncie"),
    ("terre-haute", "Indiana", "Terre Haute"),
    ("noblesville", "Indiana", "Noblesville"),
    # Missouri
    ("kansascity", "Missouri", "Kansas City"),
    ("stlouis", "Missouri", "St. Louis"),
    ("springfield-mo", "Missouri", "Springfield"),
    ("columbia-mo", "Missouri", "Columbia"),
    ("independence", "Missouri", "Independence"),
    ("lees-summit", "Missouri", "Lee's Summit"),
    ("ofallon", "Missouri", "O'Fallon"),
    ("st-joseph", "Missouri", "St. Joseph"),
    ("st-charles", "Missouri", "St. Charles"),
    ("blue-springs", "Missouri", "Blue Springs"),
    ("florissant", "Missouri", "Florissant"),
    ("joplin", "Missouri", "Joplin"),
    ("st-louis-county", "Missouri", "St. Louis County"),
    ("jackson-county", "Missouri", "Jackson County"),
    # Wisconsin
    ("milwaukee", "Wisconsin", "Milwaukee"),
    ("madison", "Wisconsin", "Madison"),
    ("green-bay", "Wisconsin", "Green Bay"),
    ("kenosha", "Wisconsin", "Kenosha"),
    ("racine", "Wisconsin", "Racine"),
    ("appleton", "Wisconsin", "Appleton"),
    ("waukesha", "Wisconsin", "Waukesha"),
    ("oshkosh", "Wisconsin", "Oshkosh"),
    ("eau-claire", "Wisconsin", "Eau Claire"),
    ("janesville", "Wisconsin", "Janesville"),
    ("west-allis", "Wisconsin", "West Allis"),
    ("la-crosse", "Wisconsin", "La Crosse"),
    ("sheboygan", "Wisconsin", "Sheboygan"),
    ("milwaukeecounty", "Wisconsin", "Milwaukee County"),
    ("dane-county", "Wisconsin", "Dane County"),
    # Maryland
    ("baltimore", "Maryland", "Baltimore"),
    ("frederick-city", "Maryland", "Frederick"),
    ("gaithersburg", "Maryland", "Gaithersburg"),
    ("rockville", "Maryland", "Rockville"),
    ("bowie", "Maryland", "Bowie"),
    ("hagerstown", "Maryland", "Hagerstown"),
    ("annapolis", "Maryland", "Annapolis"),
    ("baltimorecounty", "Maryland", "Baltimore County"),
    ("montgomerycounty", "Maryland", "Montgomery County"),
    ("pgcounty", "Maryland", "Prince George's County"),
    ("anne-arundel", "Maryland", "Anne Arundel County"),
    ("howard-county", "Maryland", "Howard County"),
    ("harford-county", "Maryland", "Harford County"),
    ("princegeorgescountymd", "Maryland", "Prince George's County"),
    # Minnesota
    ("minneapolis", "Minnesota", "Minneapolis"),
    ("saint-paul", "Minnesota", "Saint Paul"),
    ("rochester-mn", "Minnesota", "Rochester"),
    ("duluth", "Minnesota", "Duluth"),
    ("bloomington-mn", "Minnesota", "Bloomington"),
    ("brooklyn-park", "Minnesota", "Brooklyn Park"),
    ("plymouth-mn", "Minnesota", "Plymouth"),
    ("maple-grove", "Minnesota", "Maple Grove"),
    ("woodbury", "Minnesota", "Woodbury"),
    ("st-cloud", "Minnesota", "St. Cloud"),
    ("eagan", "Minnesota", "Eagan"),
    ("hennepin", "Minnesota", "Hennepin County"),
    ("ramsey", "Minnesota", "Ramsey County"),
    ("dakota-county", "Minnesota", "Dakota County"),
    ("anoka-county", "Minnesota", "Anoka County"),
    # Nevada
    ("lasvegas", "Nevada", "Las Vegas"),
    ("henderson", "Nevada", "Henderson"),
    ("reno", "Nevada", "Reno"),
    ("northlasvegas", "Nevada", "North Las Vegas"),
    ("sparks", "Nevada", "Sparks"),
    ("carson-city", "Nevada", "Carson City"),
    ("clarkcounty", "Nevada", "Clark County"),
    ("washoe", "Nevada", "Washoe County"),
    # Oregon
    ("portland", "Oregon", "Portland"),
    ("eugene", "Oregon", "Eugene"),
    ("salem", "Oregon", "Salem"),
    ("gresham", "Oregon", "Gresham"),
    ("hillsboro", "Oregon", "Hillsboro"),
    ("beaverton", "Oregon", "Beaverton"),
    ("bend", "Oregon", "Bend"),
    ("medford", "Oregon", "Medford"),
    ("springfield-or", "Oregon", "Springfield"),
    ("corvallis", "Oregon", "Corvallis"),
    ("albany-or", "Oregon", "Albany"),
    ("multnomah", "Oregon", "Multnomah County"),
    ("washington-county-or", "Oregon", "Washington County"),
    ("lane-county", "Oregon", "Lane County"),
    # Virginia
    ("virginia-beach", "Virginia", "Virginia Beach"),
    ("norfolk", "Virginia", "Norfolk"),
    ("chesapeake", "Virginia", "Chesapeake"),
    ("richmond-va", "Virginia", "Richmond"),
    ("newport-news", "Virginia", "Newport News"),
    ("alexandria", "Virginia", "Alexandria"),
    ("hampton", "Virginia", "Hampton"),
    ("roanoke", "Virginia", "Roanoke"),
    ("portsmouth", "Virginia", "Portsmouth"),
    ("suffolk", "Virginia", "Suffolk"),
    ("lynchburg", "Virginia", "Lynchburg"),
    ("harrisonburg", "Virginia", "Harrisonburg"),
    ("charlottesville", "Virginia", "Charlottesville"),
    ("fredericksburg", "Virginia", "Fredericksburg"),
    ("fairfax-county", "Virginia", "Fairfax County"),
    ("loudoun", "Virginia", "Loudoun County"),
    ("prince-william", "Virginia", "Prince William County"),
    ("henrico", "Virginia", "Henrico County"),
    ("chesterfield-va", "Virginia", "Chesterfield County"),
    # Kentucky
    ("louisville", "Kentucky", "Louisville"),
    ("lexington", "Kentucky", "Lexington"),
    ("bowling-green", "Kentucky", "Bowling Green"),
    ("owensboro", "Kentucky", "Owensboro"),
    ("covington", "Kentucky", "Covington"),
    ("jefferson-county-ky", "Kentucky", "Jefferson County"),
    # Oklahoma
    ("oklahomacity", "Oklahoma", "Oklahoma City"),
    ("tulsa", "Oklahoma", "Tulsa"),
    ("norman", "Oklahoma", "Norman"),
    ("broken-arrow", "Oklahoma", "Broken Arrow"),
    ("lawton", "Oklahoma", "Lawton"),
    ("edmond", "Oklahoma", "Edmond"),
    ("moore", "Oklahoma", "Moore"),
    ("oklahoma-county", "Oklahoma", "Oklahoma County"),
    ("tulsa-county", "Oklahoma", "Tulsa County"),
    # Louisiana
    ("neworleans", "Louisiana", "New Orleans"),
    ("baton-rouge", "Louisiana", "Baton Rouge"),
    ("shreveport", "Louisiana", "Shreveport"),
    ("lafayette-la", "Louisiana", "Lafayette"),
    ("lake-charles", "Louisiana", "Lake Charles"),
    ("kenner", "Louisiana", "Kenner"),
    ("bossier-city", "Louisiana", "Bossier City"),
    ("monroe", "Louisiana", "Monroe"),
    ("east-baton-rouge", "Louisiana", "East Baton Rouge Parish"),
    ("orleans", "Louisiana", "Orleans Parish"),
    # Connecticut
    ("hartford", "Connecticut", "Hartford"),
    ("bridgeport", "Connecticut", "Bridgeport"),
    ("new-haven", "Connecticut", "New Haven"),
    ("stamford", "Connecticut", "Stamford"),
    ("waterbury", "Connecticut", "Waterbury"),
    ("norwalk", "Connecticut", "Norwalk"),
    ("danbury", "Connecticut", "Danbury"),
    ("new-britain", "Connecticut", "New Britain"),
    ("west-haven", "Connecticut", "West Haven"),
    ("meriden", "Connecticut", "Meriden"),
    ("hartford-county", "Connecticut", "Hartford County"),
    ("fairfield-county", "Connecticut", "Fairfield County"),
    # Iowa
    ("desmoines", "Iowa", "Des Moines"),
    ("cedar-rapids", "Iowa", "Cedar Rapids"),
    ("davenport", "Iowa", "Davenport"),
    ("sioux-city", "Iowa", "Sioux City"),
    ("iowa-city", "Iowa", "Iowa City"),
    ("waterloo", "Iowa", "Waterloo"),
    ("ames", "Iowa", "Ames"),
    ("west-des-moines", "Iowa", "West Des Moines"),
    ("ankeny", "Iowa", "Ankeny"),
    ("dubuque", "Iowa", "Dubuque"),
    ("council-bluffs", "Iowa", "Council Bluffs"),
    ("polk-county", "Iowa", "Polk County"),
    # Kansas
    ("wichita", "Kansas", "Wichita"),
    ("overland-park", "Kansas", "Overland Park"),
    ("kansas-city-ks", "Kansas", "Kansas City"),
    ("olathe", "Kansas", "Olathe"),
    ("topeka", "Kansas", "Topeka"),
    ("lawrence", "Kansas", "Lawrence"),
    ("shawnee", "Kansas", "Shawnee"),
    ("manhattan-ks", "Kansas", "Manhattan"),
    ("johnson-county", "Kansas", "Johnson County"),
    ("sedgwick-county", "Kansas", "Sedgwick County"),
    # Utah
    ("saltlakecity", "Utah", "Salt Lake City"),
    ("westvalleycity", "Utah", "West Valley City"),
    ("provo", "Utah", "Provo"),
    ("west-jordan", "Utah", "West Jordan"),
    ("orem", "Utah", "Orem"),
    ("sandy", "Utah", "Sandy"),
    ("ogden", "Utah", "Ogden"),
    ("st-george", "Utah", "St. George"),
    ("layton", "Utah", "Layton"),
    ("south-jordan", "Utah", "South Jordan"),
    ("salt-lake-county", "Utah", "Salt Lake County"),
    # Nebraska
    ("omaha", "Nebraska", "Omaha"),
    ("lincoln", "Nebraska", "Lincoln"),
    ("bellevue", "Nebraska", "Bellevue"),
    ("grand-island", "Nebraska", "Grand Island"),
    ("kearney", "Nebraska", "Kearney"),
    ("douglas-county", "Nebraska", "Douglas County"),
    ("lancaster-county", "Nebraska", "Lancaster County"),
    # Alabama
    ("birmingham", "Alabama", "Birmingham"),
    ("montgomery", "Alabama", "Montgomery"),
    ("huntsville", "Alabama", "Huntsville"),
    ("mobile", "Alabama", "Mobile"),
    ("tuscaloosa", "Alabama", "Tuscaloosa"),
    ("hoover", "Alabama", "Hoover"),
    ("dothan", "Alabama", "Dothan"),
    ("auburn", "Alabama", "Auburn"),
    ("jefferson-county-al", "Alabama", "Jefferson County"),
    ("madison-county-al", "Alabama", "Madison County"),
    # South Carolina
    ("columbia-sc", "South Carolina", "Columbia"),
    ("charleston-sc", "South Carolina", "Charleston"),
    ("north-charleston", "South Carolina", "North Charleston"),
    ("mount-pleasant", "South Carolina", "Mount Pleasant"),
    ("rock-hill", "South Carolina", "Rock Hill"),
    ("greenville-sc", "South Carolina", "Greenville"),
    ("summerville", "South Carolina", "Summerville"),
    ("spartanburg", "South Carolina", "Spartanburg"),
    ("richland-county", "South Carolina", "Richland County"),
    ("charleston-county", "South Carolina", "Charleston County"),
    ("greenville-county", "South Carolina", "Greenville County"),
    # New Jersey
    ("newark", "New Jersey", "Newark"),
    ("jersey-city", "New Jersey", "Jersey City"),
    ("paterson", "New Jersey", "Paterson"),
    ("elizabeth", "New Jersey", "Elizabeth"),
    ("edison", "New Jersey", "Edison"),
    ("woodbridge", "New Jersey", "Woodbridge"),
    ("hamilton-nj", "New Jersey", "Hamilton"),
    ("lakewood", "New Jersey", "Lakewood"),
    ("toms-river", "New Jersey", "Toms River"),
    ("trenton", "New Jersey", "Trenton"),
    ("camden", "New Jersey", "Camden"),
    ("clifton", "New Jersey", "Clifton"),
    ("bergen-county", "New Jersey", "Bergen County"),
    ("middlesex-county-nj", "New Jersey", "Middlesex County"),
    ("essex-county", "New Jersey", "Essex County"),
    ("ocean-county", "New Jersey", "Ocean County"),
    # Idaho
    ("boise", "Idaho", "Boise"),
    ("nampa", "Idaho", "Nampa"),
    ("meridian", "Idaho", "Meridian"),
    ("idaho-falls", "Idaho", "Idaho Falls"),
    ("pocatello", "Idaho", "Pocatello"),
    ("caldwell", "Idaho", "Caldwell"),
    ("coeur-dalene", "Idaho", "Coeur d'Alene"),
    ("ada-county", "Idaho", "Ada County"),
    # New Mexico
    ("albuquerque", "New Mexico", "Albuquerque"),
    ("las-cruces", "New Mexico", "Las Cruces"),
    ("rio-rancho", "New Mexico", "Rio Rancho"),
    ("santa-fe", "New Mexico", "Santa Fe"),
    ("roswell", "New Mexico", "Roswell"),
    ("bernalillo", "New Mexico", "Bernalillo County"),
    # New Hampshire
    ("manchester-nh", "New Hampshire", "Manchester"),
    ("nashua", "New Hampshire", "Nashua"),
    ("concord-nh", "New Hampshire", "Concord"),
    ("derry", "New Hampshire", "Derry"),
    # Rhode Island
    ("providence", "Rhode Island", "Providence"),
    ("cranston", "Rhode Island", "Cranston"),
    ("woonsocket", "Rhode Island", "Woonsocket"),
    ("pawtucket", "Rhode Island", "Pawtucket"),
    ("east-providence", "Rhode Island", "East Providence"),
    # West Virginia
    ("charleston-wv", "West Virginia", "Charleston"),
    ("huntington", "West Virginia", "Huntington"),
    ("morgantown", "West Virginia", "Morgantown"),
    ("parkersburg", "West Virginia", "Parkersburg"),
    # Montana
    ("billings", "Montana", "Billings"),
    ("missoula", "Montana", "Missoula"),
    ("great-falls", "Montana", "Great Falls"),
    ("bozeman", "Montana", "Bozeman"),
    ("butte", "Montana", "Butte"),
    # Wyoming
    ("cheyenne", "Wyoming", "Cheyenne"),
    ("casper", "Wyoming", "Casper"),
    ("laramie", "Wyoming", "Laramie"),
    # North Dakota
    ("fargo", "North Dakota", "Fargo"),
    ("bismarck", "North Dakota", "Bismarck"),
    ("grand-forks", "North Dakota", "Grand Forks"),
    ("minot", "North Dakota", "Minot"),
    # South Dakota
    ("sioux-falls", "South Dakota", "Sioux Falls"),
    ("rapid-city", "South Dakota", "Rapid City"),
    ("aberdeen-sd", "South Dakota", "Aberdeen"),
    # Delaware
    ("wilmington", "Delaware", "Wilmington"),
    ("dover", "Delaware", "Dover"),
    ("newark-de", "Delaware", "Newark"),
    ("new-castle-county", "Delaware", "New Castle County"),
    # Maine
    ("portland-me", "Maine", "Portland"),
    ("lewiston", "Maine", "Lewiston"),
    ("bangor", "Maine", "Bangor"),
    ("auburn-me", "Maine", "Auburn"),
    # Vermont
    ("burlington-vt", "Vermont", "Burlington"),
    ("south-burlington", "Vermont", "South Burlington"),
    ("rutland", "Vermont", "Rutland"),
    # Hawaii
    ("honolulu", "Hawaii", "Honolulu"),
    ("pearl-city", "Hawaii", "Pearl City"),
    ("hilo", "Hawaii", "Hilo"),
    ("hawaii-county", "Hawaii", "Hawaii County"),
    # Alaska
    ("anchorage", "Alaska", "Anchorage"),
    ("fairbanks", "Alaska", "Fairbanks"),
    ("juneau", "Alaska", "Juneau"),
    ("matsu", "Alaska", "Matanuska-Susitna Borough"),
    # Arkansas
    ("little-rock", "Arkansas", "Little Rock"),
    ("fort-smith", "Arkansas", "Fort Smith"),
    ("fayetteville-ar", "Arkansas", "Fayetteville"),
    ("springdale", "Arkansas", "Springdale"),
    ("jonesboro", "Arkansas", "Jonesboro"),
    # Mississippi
    ("jackson-ms", "Mississippi", "Jackson"),
    ("gulfport", "Mississippi", "Gulfport"),
    ("southaven", "Mississippi", "Southaven"),
    ("hattiesburg", "Mississippi", "Hattiesburg"),
    ("biloxi", "Mississippi", "Biloxi"),
    ("meridian-ms", "Mississippi", "Meridian"),
    # Colorado (extra)
    ("denver", "Colorado", "Denver"),
    ("colorado-springs", "Colorado", "Colorado Springs"),
    ("aurora-co", "Colorado", "Aurora"),
    ("fort-collins", "Colorado", "Fort Collins"),
    ("lakewood", "Colorado", "Lakewood"),
    ("thornton", "Colorado", "Thornton"),
    ("arvada", "Colorado", "Arvada"),
    ("westminster", "Colorado", "Westminster"),
    ("pueblo", "Colorado", "Pueblo"),
    ("centennial", "Colorado", "Centennial"),
    ("boulder", "Colorado", "Boulder"),
    ("greeley", "Colorado", "Greeley"),
    ("longmont", "Colorado", "Longmont"),
    ("loveland", "Colorado", "Loveland"),
    ("broomfield", "Colorado", "Broomfield"),
    ("castle-rock", "Colorado", "Castle Rock"),
    ("commerce-city", "Colorado", "Commerce City"),
    ("denver-county", "Colorado", "Denver County"),
    ("jefferson-county-co", "Colorado", "Jefferson County"),
    ("arapahoe", "Colorado", "Arapahoe County"),
    ("adams-county", "Colorado", "Adams County"),
    # Metro/Regional
    ("lametro", "California", "LA Metro"),
    ("metro", "Oregon", "Metro Portland"),
    ("kingcountywa", "Washington", "King County"),
    ("mwrd", "Illinois", "Metropolitan Water Reclamation"),
    ("cta", "Illinois", "Chicago Transit Authority"),
    ("rtd", "Colorado", "RTD Denver"),
    ("sfmta", "California", "SF MTA"),
    ("bart", "California", "BART"),
    ("scag", "California", "SCAG"),
    ("sandag", "California", "SANDAG"),
    ("sacog", "California", "SACOG"),
    ("campo", "California", "CAMPO"),
    ("abag", "California", "ABAG"),
    ("mtc", "California", "MTC"),
]

def test_slug(args):
    slug, state, name = args
    if slug in existing:
        return None  # Already have it
    url = f"https://webapi.legistar.com/v1/{slug}/Events?$top=1"
    try:
        r = requests.get(url, headers=HEADERS, timeout=TIMEOUT)
        if r.status_code == 200 and len(r.content) > 50:
            ct = r.headers.get("Content-Type", "")
            # Check it's real data not an error page
            if "json" in ct or "xml" in ct:
                return (slug, state, name)
        return None
    except Exception:
        return None

print()
print(Fore.CYAN + "="*60)
print(Fore.CYAN + f"  Discovering new Legistar slugs...")
print(Fore.CYAN + f"  Testing {len(CANDIDATES)} candidates")
print(Fore.CYAN + f"  ({len(existing)} already known, skipping those)")
print(Fore.CYAN + "="*60)
print()

# Filter out already known
to_test = [(s, st, n) for s, st, n in CANDIDATES if s not in existing]
print(f"  Testing {len(to_test)} new candidates...")
print()

found = []
with ThreadPoolExecutor(max_workers=20) as ex:
    futures = {ex.submit(test_slug, c): c for c in to_test}
    done = 0
    for future in as_completed(futures):
        done += 1
        result = future.result()
        if result:
            slug, state, name = result
            found.append(result)
            print(Fore.GREEN + f"  FOUND  {slug:30s} ({name}, {state})")
        if done % 50 == 0:
            print(Fore.CYAN + f"  Progress: {done}/{len(to_test)} tested, {len(found)} found so far...")

print()
print(Fore.CYAN + "="*60)
print(Fore.GREEN + f"  Found {len(found)} new working slugs!")
print(Fore.CYAN + "="*60)

if found:
    # Auto-add to legistar.py
    with open("scrapers/legistar.py", "r") as f:
        content = f.read()

    additions = "\n    # Auto-discovered new slugs\n"
    for slug, state, name in sorted(found, key=lambda x: x[1]):
        line = f'    "{slug}":{" "*(20-len(slug))}("{state}", "{name}"),\n'
        if f'"{slug}"' not in content:
            additions += line

    # Add before the _EXTRA section
    if "_EXTRA = {" in content:
        content = content.replace("_EXTRA = {", additions + "\n_EXTRA = {")
    else:
        # Add before closing brace of LEGISTAR_CITIES
        content = content.replace(
            "}\n\n# ── Lookup",
            additions + "}\n\n# ── Lookup"
        )

    with open("scrapers/legistar.py", "w") as f:
        f.write(content)

    print()
    print(Fore.GREEN + f"  Auto-added to scrapers/legistar.py")
    print()
    print("  New slugs found:")
    for slug, state, name in found:
        print(f"    {slug} ({name}, {state})")

print()
print(Fore.CYAN + "  Run python run.py to start collecting from all discovered cities")
print()
